### ISSUE TITLE
Adhere to home assistant 2023.8 mqrr changes

### ISSUE THREAD

**Issue by fredrike** [quazzie/tellstick-plugin-mqtt-hass#41]
Home assistant 2023.8 have started to complain about duplicate names, we need to fix that..

https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

https://www.hackster.io/news/home-assistant-2023-8-brings-new-mqtt-related-error-messages-but-don-t-worry-say-maintainers-bec84d16710e

![Screenshot_20230804-100809](https://github.com/quazzie/tellstick-plugin-mqtt-hass/assets/676999/082b8d57-e9a2-4e74-a8e7-db55a9482740)

I guess that we need to remove the device Name (`Krypgrund ` in this example..

```yaml
{
  "unit_of_measurement": "%",
  "device": {
    "suggested_area": "",
    "name": "Krypgrund",
    "identifiers": "90d03311-23c9-4f67-a937-b86d89d707e4",
    "via_device": "ACCA5401B5EA",
    "model": "Temperaturehumidity",
    "manufacturer": "Mandolyn"
  },
  "device_class": "humidity",
  "name": "Krypgrund humidity",
  "state_class": "measurement",
  "state_topic": "home/sensor/TellstickZnetLite/5_2_0/state",
  "value_template": "{{ value_json.value }}",
  "availability_topic": "home/binary_sensor/TellstickZnetLite/hub/state",
  "unique_id": "ACCA5401B5EA_5_2_0",
  "platform": "mqtt"
}
```
